### ISSUE TITLE
Text overflowing out of alert

### ISSUE THREAD

**Issue by shivansal** [zahidalidev/toastify-react-native#13]
![image](https://github.com/zahidalidev/toastify-react-native/assets/15356251/f3e714c1-f171-49d2-863a-a543ce689921)

Running into an issue where the text is overflowing. Isn't it supposed to automatically wrap? Thoughts ?

**Comment by seba9999** [comment]
Why did you close this ? Did you find some workaround ?

**Comment by jduhking** [comment]
> Why did you close this ? Did you find some workaround ?

Simply increase the width of the alert or reduce the font Size.
Regardless, its a toast which should be made for simple messages / errors.

You can change the width of the toast using the width prop in the ToastManager or by changing width in the style prop in the ToastManager

**Comment by seba9999** [comment]
Well we could have a Toast with 2 lines... It still is a simple message !
The little cross is messing our text here... I've done some ugly work-around with some margin-right on my text for now ..

**Comment by LorenDorez** [comment]
I ran into a simialr issue but just adjusted it with the style prop by setting height to auto, below is a code snippet in case it helps others

`<ToastManager theme={theme} duration={10000} style={{height: 'auto', width: '90%'}} />`
