### ISSUE TITLE
Progress bar cannot run smoothly

### ISSUE THREAD

**Issue by hanifmhd** [zahidalidev/toastify-react-native#2]
Hi,

Thanks for the creating of this library, it is really helpful.
I got an issue about progress bar that cannot run smoothly, i set the duration to 3000 and after toast is finished, the keyboard will show up. Probably you can help me.

Thank you.

https://user-images.githubusercontent.com/15220788/145150956-abbe9257-54f5-47e7-a563-c3d8d8bd52a3.mov

**Comment by zahidalidev** [comment]
Thanks,
I will fix it as soon as I can.

**Comment by zahidalidev** [comment]
This issue has been resolved in version 3.1.0. Let us know if you still face this issue
