### ISSUE TITLE
Error: Unable to resolve module react-native-modal 

### ISSUE THREAD

**Issue by arsalannury** [zahidalidev/toastify-react-native#20]
Hi. I hope you are well. after installing the package I have an error with react-native-modal. 
this is my package version "toastify-react-native": "^4.0.0",

**Comment by 4myr** [comment]
just install react-native-modal using:
`npx expo install react-native-modal`

you may also get `Unable to resolve "react-native-responsive-fontsize"` error, you should install it too by:
`npx expo install react-native-responsive-fontsize `

**Comment by rossparachute** [comment]
On _expo:53.0.22_ with _toastify-react-native:5.0.0_ had to install _react-native-modal_, _react-native-responsive-fontsize_ and _react-native-vector-icons_, to resolve:

_Unable to resolve "react-native-responsive-fontsize" from "node_modules/toastify-react-native/components/ToastManager.tsx"_
