### ISSUE TITLE
Close Icon

### ISSUE THREAD

**Issue by AguaPotavel** [zahidalidev/toastify-react-native#21]
`ios-close-outline`
no longer exist on lib **react-native-vector-icons** 

On ToastManager.js
```js
<TouchableOpacity onPress={this.hideToast} activeOpacity={0.9} style={styles.hideButton}>
            <Icon name='ios-close-outline' size={22} color={Colors[theme].text} />
</TouchableOpacity>
```

replace with

`close-outline`

**Comment by zahidalidev** [comment]
@AguaPotavel Thanks for pointing, will update the package.

**Comment by Zrna** [comment]
Merged → https://github.com/zahidalidev/toastify-react-native/pull/26
