### ISSUE TITLE
Hide progress bar

### ISSUE THREAD

**Issue by jduhking** [zahidalidev/toastify-react-native#22]
Is there any way to remove the status bar?

**Comment by zahidalidev** [comment]
@jduhking not yet.

**Comment by jduhking** [comment]
> @jduhking not yet.

I see, how hard do you think it would be to add an option to hide it?

**Comment by zahidalidev** [comment]
@jduhking I don't think it will be difficult, we need to add the prop and based on that we can conditionally render the progress bar.

**Comment by nico-gao** [comment]
I had the same questions, but then I found setting duration to 0 worked out.

**Comment by Zrna** [comment]
The feature is added in this PR — https://github.com/zahidalidev/toastify-react-native/pull/37 (merged).  

To hide the progress bar use it like this:
```jsx
<ToastManager
  showProgressBar={false}
/>
```

We are currently waiting for a new npm version that will contain the changes.

**Comment by Zrna** [comment]
The feature is available in the >5.0.1 versions.
