### ISSUE TITLE
Unwanted question mark in the modal ??

### ISSUE THREAD

**Issue by devabhi01** [zahidalidev/toastify-react-native#25]
Why there is unwanted question mark in the modal ??
![error](https://github.com/zahidalidev/toastify-react-native/assets/91911787/fa1fc8fb-426d-43f3-af3c-7952794e74f5)

**Comment by devabhi01** [comment]
solevd!! I just have to update your pakage in the node modules from ios-close-outline to close-outline.
Thanks this pakage is really helpful.

**Comment by zahidalidev** [comment]
Thanks @devabhi01 for pointing it out, I have updated the package and published new release.
