### ISSUE TITLE
IOS - Font error

### ISSUE THREAD

**Issue by JeMorini** [zahidalidev/toastify-react-native#3]
Hello, I have an error in the font in the ios project

- Images

[https://drive.google.com/file/d/14yfnwQH3NhzH-wFDxqGYgwL5HOmyuA0z/view?usp=sharing](url)

[https://drive.google.com/file/d/1tHdSzJKGVKifM82azCHTb-Cu2RNQn4Y8/view?usp=sharing](url)

I have correction suggestions, I can create a pull request if you prefer.

Thanks for your lib!

**Comment by zahidalidev** [comment]
@JeMorini yeah, you can create a pull request. Thanks.

**Comment by Ahmedhamed77** [comment]
yeah the same issue here, how did you fix it?

**Comment by zahidalidev** [comment]
This issue has been resolved in version 3.1.0.
