### ISSUE TITLE
After installation facing issuue

### ISSUE THREAD

**Issue by 8358rahul** [zahidalidev/toastify-react-native#6]
error: Error: Unable to resolve module react-native-modal from E:\live_cafeapp\node_modules\toastify-react-native\components\ToastManager.js: react-native-modal could not be found within the project or in these directories:

**Comment by 8358rahul** [comment]
issue

**Comment by zahidalidev** [comment]
@8358rahul Please share more details like your package.json

**Comment by pablohenriqueop** [comment]
Im facing the same problem. I just installed the package following the steps but does not work.

**Comment by pablohenriqueop** [comment]
@zahidalidev To solve the problem i had to add `react-native-modal`, `react-native-responsive-fontsize` and `react-native-paper` deps to make it works.

**Comment by djaffer** [comment]
the readme should say that clearly
