### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by PatoGordo** [zahidalidev/toastify-react-native#8]
Create the types definition of the library

**Comment by dsursulino** [comment]
npm i --save-dev @types/toastify-react-native  do we have the types to run in typescript?

**Comment by zahidalidev** [comment]
Not yet, we are working on it

**Comment by ZiyadNab** [comment]
when please \:

**Comment by zahidalidev** [comment]
Added typescript support in **version 4.0.0**

**Comment by mikheyrojo** [comment]
Am I missing something, or types are not exported?
